### ISSUE TITLE
tvm-clj documentation for numerical computation?

### ISSUE THREAD

**Issue by lungsi** [techascent/tvm-clj#15]
Hi,

After hearing Chris Nuernberger on [podcast](https://www.therepl.net/episodes/13/) I am interested in using tvm-clj for doing numerics on my Clojure projects.

At the moment my main use case is numerical computation / vectorized computations, i.e., system of equations for my 'bespoke' research problems. I do not currently plan to use tvm-clj for machine/deep learning. I am looking for high performance matrix computation (not linear algebra decomposition and solving equations).

Could someone kindly direct me to the documentation on performing/mechanics of computation operations? Or are most of the transformations and computation operation done by `core.matrix` library and tvm-clj is mainly responsible for compiling them and does not handle these operations.

Regards.

**Comment by cnuernber** [comment]
tvm-clj doesn't use core.matrix at all aside as a mechanism to create inputs.  

tvm is a numerics compiler and as such it allows you to write and optimize the computations such as [generalized matrix matrix multiplication](https://github.com/dmlc/tvm/tree/master/tutorials/optimize).

You can use it to write and optimize the entire computation graph at once, not operation by operation, so for example you may have several elementwise operations, a matrix operation and a reduction of sorts and you could schedules these in different ways depending on how you intended to use the cache structure of the hardware you are running on.

The way it works is that you write an AST description of what you want to do and then schedule different parts of the computation graph so that you can take advantage of various types of tiling or shared memory or reoganization of your computation without needing to re-write your algorithm itself.

Using tvm-clj is one way to use tvm.  It is also possible to use tvm via clojure by using [libpython bindings](https://github.com/cnuernber/libpython-clj) potentially extending what Alan Marazzi started with [pathera](https://github.com/alanmarazzi/panthera).   Using tvm via the existing python API gives you access to more examples and autotvm which is the autotuning system for tvm.

**Comment by cnuernber** [comment]
Closing this, thanks for the issue!
